L25E.16 RC0:
Please note: kernel branch "p-android-2.6.29" is used in this
manifest. There is no need to use "manual_merges.sh" file
anymore.

Hos to clone the source:

mkdir <your directory path>
cd <your directory path>
mkdir mydroid
cd mydroid
export MYDROID=`pwd`
repo init -u git://git.omapzoom.org/platform/omapmanifest.git -b <commit>
repo sync

where "commit" is the corresponding commit id for this manifest.

for alternatives about getting source code please look at:
http://www.omappedia.org/wiki/Android_Getting_Started#Stable_Release

for booting instructions see:
http://www.omappedia.org/wiki/Android_Getting_Started#Installing_Android

-----------------------------------

Patches Merged for L25E.16 RC0:

|platform/external/opencore
1879|Increased MaxClockCorrection from 100 to 1000.
1869|OpenCore fix for video stutter in high resolution clips
1761|TI Patch:  Add support for 720p playback and thumbnails
1662|Increasing the VIDEO_INTERLEAVE_BUFFER_SIZE for 720p encoding.  Porting patch from Donut to Eclair
1567|Open Core: Fix in author driver component for bitrate handling
1538|TI OpenCORE: Increase the max buffer size to be use while streaming.
1480|Fix compilation error in OC
1479|Updated the supported bitrates
1478|Changed the max and min values supported by the camcorder. Also took care of the bitrate settings. Signed-off-by: Anu Sundararajan
<sanuradha@ti.com>
1477|Updated the maximum FPS supported by AuthorDriver.
1472|Setting the correct format for zoom2
1458|Use the correct video format - YUV 422 UYVY

|platform/hardware/ti/omx
1824|CR Fix: Replace Unused "Case" Stamtement by "Default" Statements in Video Decoder
1700|CR Fix: Change #if 0 to #ifdef DEBUG and Remove #if 1 in OMX Video Decoder
1886|Remove LoadBaseImage() function from JPEG Test Application
1870|DR Fix: Fix for the Video Stagefright test
1794|VideoDecoder - SN integration changes
1802|Revert "AAC Encoder: OMX_GetState handling as blocking call"
1800|CR: Small Fix in OMX Video to get error value
1790|CR Fix: Update for MPEG4/H263 and H264 SN interface
1792|ti_omx_config_parser: Fix KW defect
1787|adding 3630 1GHz support for OMX RM: eclair
1645|OMX: g726 decoder kw fixes.
1710|OMX: AAC Encoder UNDER_CE MACRO removal.
1769|OMX JPEG Decoder changes for DSP Socket Node 3.9 migration.
1640|This patch will fix the JPEG_ENC stand-alone test application hang issue after completing the test execution.
1768|OMX JPEG Encoder changes for DSP Socket Node 3.9 migration.
1757|DR Fix: OMX Video Decoder: Clean up OMX_EmptyBufferDone() and OMX_FillBufferDone()
1714|CR Fix: Remove UNDER_CE Blocks in OMX Command Line Application
1706|OMX: AAC Encoder kw fixes.
1668|OMX: g729 Encoder kw fixes.
1663|OMX: g726 Encoder kw fixes.
1635|WMA decoder Klocwork changes.
1634|G722 Encoder Klockwork changes
1633|OMX-AUDIO: WBAMR Encoder Klockwork fixes and remove UNDER_CE code
1632|G722 decoder Klockwork changes
1631|OMX-AUDIO: WBAMR Decoder Klockwork fixes and remove UNDER_CE code
1630|G711 Decoder Klockworks changes
1629|OMX-AUDIO: NBAMR Encoder Klockwork fixes and remove UNDER_CE code
1628|MP3 decoder Klockwork changes
1627|OMX-AUDIO: NBAMR Decoder Klockwork fixes and remove UNDER_CE code
1639|Fix for Klockwork defect id 314 in project WS_3430_OMX_Linux_25_M. issue: Missing unlock for a variable in else condition.
1637|Fix for Klockwork defect id 289 in project WS_3430_OMX_Linux_25_M. Issue: Pointer will be dereferenced after it was positively checked for NULL.
1701|CR Fix: Change #if 0 to #ifdef DEBUG and Remove #if 1 in OMX Video Decoder Application
1660|CR: Fix for Klocwork issues in OMX-Video component
1695|CR: Video Decoder, make use of OMX_MEMFREE_STRUCT_DSPALIGN() and fix mem leaks.
1460|AAC decoder Klockwork Changes.
1711|Eclair: Application VidDecTest_common Uses a Hardcoded Max Buffer's Number. Instead It Should Use a Number Defined in Overlay
1753|correcting opp values for 3430
1704|CR Fix: Validate Arguments in Circular Buffer and Queue Functions
1703|CR Fix: Be Consistent and Use Macro OMX_CONF_CHECK_CMD to Validate Arguments
1702|CR Fix: Correct Memory Handling Findings
1698|CR Fix: Correct the Spelling of Word "Frequency" in VIDDEC_GetRMFrequency
1697|CR Fix: Remove Commented Code in Video Decoder's Application
1696|CR: OMX Video ENCODER: Address assignment was incorrect for finding the supported profile and level.
1687|CR Fix: Remove UNDER_CE Blocks in OMX Decoder
1742|OMX_AUDIO: WMA Decoder interface changes to move to latest DSP labels.
1720|OMX_AUDIO: AAC Decoder interface changes to move to latest DSP labels.
1739|OMX_AUDIO: MP3 Decoder interface changes to move to latest DSP labels.
1733|LCML: Adding macro for interface changes of the DSP .
1636|WMA decode review changes.
1643|Video Decoder: Use TI standard logging
1649|CR: Video Decoder, add error logs from LCML_Callback()
1648|CR: Video Decoder, Replace when posible 'if' conditions for 'else if' at VIDDEC_LCML_Callback.
1646|CR: OMX Video Decoder: Address assignment was incorrect for finding the supported profile and level.
1644|CR: OMX Video Decoder: Remove OMX_CONF_SET_ERROR_BAIL
1642|CR: OMX Video Decoder: Add error handling for DSP Initialization

|platform/vendor/ti/zoom2
1819|Bluetooth: 1:Adding UIM Service in init.omapzoom.rc and omapzoom2-mmc.rc 2. Adding the BUILD_HOTPLUG in the BoardConfig.mk
1804|Load the SGX driver at start up
1447|Boot argument files for NAND boot.
1468|Enabling CameraHal

|platform/hardware/ti/omap3
1785|    Bluetooth: 1)User space init manager for Shared Transport (UIM)
1786|Smooth digital zoom added.
1511|[FM Radio] Upgradiation of FM stack from M3 to M5 version from MCS
1762|Change missing in #1620 patch set 2. Re committing it since #1620 is already integrated. THis has to be used along with #1620
1620|Fixes Snapshot, IMAGE_PROCESSING_PIPELINE compile time flag is set correctly, malloc is used for the capture buffers instead of shared memory,
little code clean-up
1516|Problem: Preview get froze randomly after few continuous image captures. Cause: In CapturePicture() function after the capture it tries to queue
the buffer without checking whether that buffer index is de-queued ot not. Fix: Removed those queueBuffer call
1508|Alsa_sound: Routing mic for recording
1616|Ported Patch#1374 from donut to eclair Camerahal: Changed the buffer allocation
1571|Small change to inc queue buffer after error check
1471|CameraHal-camcorder: Code clean up
1470|Set the default format as yuv 422 uyvy
1459|Syncing with the latest overlay on Google Tree
1469|Merge commit 'refs/changes/41/1441/1' of ssh://sanuradha@review.omapzoom.org:29418/platform/hardware/ti/omap3 into HEAD
1444|CameraHal: Close pipes for MessageQueue and threads
1441|Update and adapt CameraHal from L25.14RC9 to Eclair

|platform/packages/apps/Camera
1814|Added support for Contrast, Brightness, Saturation, Shaprness, Exposure Compensation, Exposure, Capture mode, CAF, ROTATION and ISO in Camera
application
1813|Additional picture resolutions added in sync with CameraHAL
1812|Touch Focus support added
1811|Low Light support added
1763|Added options for frame rate and preview resolution in the application
1705|Disabling camcorder application in main menu
1626|IPP configuration option added
1728|Burst capture support added, PPM changes integrated, key event "F" set for autofocus, key event "P" set for capture
1624|Camera<->Camcorder switch fix
1569|Changes to support Camcorder app menu options
1568|Enabling camcorder application in main menu

|platform/hardware/alsa_sound
1507|Alsa_sound: Recorder hangs when stops the recording.

|platform/frameworks/base
1855|framework/base: Enable the getPosition() API
1527|SoundRecorder: Adding support for wb_amr encoder sampling rate.
1572|Setting mOverlay to 0 after destroying it

|platform/system/wlan/ti
1876|WLAN - WPS security fix
1838|WLAN - Updating WiLink driver version to M5.01
1835|WLAN - Updating comment headers with 2010 date
1619|WLAN - Driver and CLI changes for supporting WPS
1519|WLAN - Removing check in data path
1488|WLAN - Adding wake_lock APIs
1463|WLAN - Fixing manual mode issue

|platform/bionic
1252|SMP: remove swp as its not smp safe

|platform/packages/apps/SoundRecorder
1526|SoundRecorder: Adding Enocder selection from UI

|platform/external/wpa_supplicant
1618|WLAN - WPS Security type support Added

|kernel/omap
1834|Bluetooth: ZOOM2: Enabling support for BT shared Transport in defconfig
1832|Drivers: Misc: Correct config flag in W1127x-rfkill.c
1831|Drivers: misc: Correct Config flag to CONFIG_TI_ST_BT
1830|OMAP3630: SDP: Remove mach/usb-ohci.h from board file
1817|Bluetooth: ZOOM3: Enabling support for BT shared Transport
1781|OMAP3: ZOOM2 :add BT/FM/GPS combo platform device
1797|Bluetooth: prevent the wl127x-rfkill driver to acquire the GPIO 109
1818|Bluetooth: Adding Build option for BT shared Transport
1780|bluetooth: BT driver using ST for TI combo devices
1779|drivers: misc: sources for FM header file
1778|drivers: misc: sources for ST header file
1777|drivers: misc: sources for HCI LL PM protocol
1776|drivers: misc: sources for ST core
1775|drivers: misc: sources for Init manager module
1774|drivers: misc: Kconfig, Makefile for TI's ST ldisc
1773|drivers: misc: add new TI shared transport ldisc
1772|serial: TTY: new ldisc for TI BT/FM/GPS chips
1821|USB: Enable interrupts on pullup
991|OMAP3: PM: decrease cpufreq transition latency
1806|USB: Enable interrupts on pullup
1767|OHCI: remove mach/usb-ohci.h and use mach/usb.h instead
1789|omap mailbox: Flush posted writes on IRQ ACK
1788|OMAP3: PM: SR Flush posted writes on IRQ
1716|USB: 3630sdp default OHCI and EHCI as modules
1394|V4L2: Adding 3630 specific PM constraints to video driver
1591|OMAP NAND: Remove CONFIG_MTD_NAND_OMAP_HWECC from configs
1590|OMAP: NAND: Making hw ecc compatible with romcode ecc
1589|OMAP NAND: Selection of hw/sw ecc from platform data
1650|UART: Restore MCR register value on wake up
1679|OMAP3: PM CORE OFF notification api
1694|OHCI: enabe OHCI in 3630sdp defconfig
1692|OHCI: set tranceiver RCV pin to safe mode
1693|OHCI: added ohci init function in 3630 board file
1691|OHCI: Disabled MMC2 mux from board support
1690|OHCI: 3630SDP: enabling Philips ISP1301 in Host mode
1689|OHCI: 3630SDP: Register ISP1301 USB Tranceiver in board file
1688|OMAP3630: Enabling USB storage in 3630sdp defconfig
1667|OMAP3:DSS: enable clk at the right place
1655|OMAP3:PM:OSwR add sysfs entry to enable/disable OSwR
1654|OMAP3:PM: And debug state counter for OSwR
1653|OMAP3:PM: Uart prepare idle changes across OSWR/OFF
1652|OMAP3:PM: DPLL4 autoidle handling across OsWR
1651|OMAP3:PM: OSWR feature addition
1400|OHCI: force the domain to Idle/Standby while disabling the f-clocks
1525|Hsmmc: update error handling
1452|defconifg: enable smsc driver for zoom platform
1451|smsc: sync up with .33-rc1 kernel
1450|zoom2/3: register smsc driver for ethernet
1504|Hsmmc:Handle card removal during suspend

Signed-off-by: Luis Gonzalez <lgonzalez@ti.com>